#Remove-Item –path ./ –recurse

Invoke-WebRequest -Uri 'https://api.cloudmersive.com/phishing/v1/swagger.json' -OutFile '.\phishing-api-swagger.json'
(Get-Content .\phishing-api-swagger.json).replace('localhost', "api.cloudmersive.com") | Set-Content .\phishing-api-swagger.json
(Get-Content .\phishing-api-swagger.json).replace('"http"', '"https"') | Set-Content .\phishing-api-swagger.json

& java -jar swagger-codegen-cli-2.4.14.jar generate -i .\phishing-api-swagger.json -l go -c packageconfig.json
# $extrasetup = (Get-Content ./extrasetup.py) -join "`n"
# Write-Host $extrasetup
# (Get-Content ./setup.py).replace('# http://pypi.python.org/pypi/setuptools', $extrasetup) | Set-Content ./setup.py
# (Get-Content ./setup.py).replace('"""\', "long_description,`n    long_description_content_type='text/markdown'") | Set-Content ./setup.py
# (Get-Content ./setup.py).replace('The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.  # noqa: E501', '') | Set-Content ./setup.py
# (Get-Content ./setup.py).replace('    """', '') | Set-Content ./setup.py
(Get-Content ./README.md).replace('This Python package is automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project:', 'This Go package provides a native API client for [Cloudmersive Phishing Detection API](https://cloudmersive.com/phishing-detection-api)') | Set-Content ./README.md
Write-Host "Done."