/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersivePhishingApiClient

// Result of detecting phishing using AI for basic text string analysis
type PhishingDetectionTextStringResponse struct {
	// True if the result is not phishing (clean), and false otherwise
	CleanResult bool `json:"CleanResult,omitempty"`
	// Confidence level between 0.0 and 1.0 where values over 0.9 indicate high confidence
	ConfidenceLevel float64 `json:"ConfidenceLevel,omitempty"`
	// Rationale for why the conclusion was formed
	AnalysisRationale string `json:"AnalysisRationale,omitempty"`
}
