/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersivePhishingApiClient

// Result of detecting phishing using AI
type PhishingDetectionEmailAdvancedResponse struct {
	// True if the result is not phishing (clean), and false otherwise
	CleanResult bool `json:"CleanResult,omitempty"`
	// Overall phishing risk level between 0.0 and 1.0
	PhishingRiskLevel float64 `json:"PhishingRiskLevel,omitempty"`
	// Overall phishing spam level between 0.0 and 1.0
	SpamRiskLevel float64 `json:"SpamRiskLevel,omitempty"`
	// True if the input email is from a low reputation sender
	ContainsLowReputationSender bool `json:"ContainsLowReputationSender,omitempty"`
	// True if the input email contains phishing threat risks, false otherwise
	ContainsPhishing bool `json:"ContainsPhishing,omitempty"`
	// True if the email contains phishing threat risks, false otherwise
	ContainsSpam bool `json:"ContainsSpam,omitempty"`
	// True if the input email contains unsolicited sales, false otherwise
	ContainsUnsolicitedSales bool `json:"ContainsUnsolicitedSales,omitempty"`
	// True if the input email contains promotional content, false otherwise
	ContainsPromotionalContent bool `json:"ContainsPromotionalContent,omitempty"`
	// True if the input email contains a phishing attempt, false otherwise
	ContainsPhishingAttempt bool `json:"ContainsPhishingAttempt,omitempty"`
	// Rationale for why the conclusion was formed
	AnalysisRationale string `json:"AnalysisRationale,omitempty"`
}
