/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersivePhishingApiClient

// Request to detect phishing from an email
type AdvancedEmailDetectionRequest struct {
	// Email address of the sender
	FromEmailAddress string `json:"FromEmailAddress,omitempty"`
	// Email address of the recipient
	ToEmailAddress string `json:"ToEmailAddress,omitempty"`
	// Subject of the email
	Subject string `json:"Subject,omitempty"`
	// Body of the email in HTML, or text
	HtmlBody string `json:"HtmlBody,omitempty"`
	// Allow email from low reputation senders and domains
	AllowLowReputationSenders bool `json:"AllowLowReputationSenders,omitempty"`
	// True to allow sanctioned countries and certain known sanctioned entities, false otherwise (default)
	AllowSanctioned bool `json:"AllowSanctioned,omitempty"`
	// Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
	CustomPolicyID string `json:"CustomPolicyID,omitempty"`
	// Optional: Input email file bytes (EML, PDF, etc.).  If not provided, HtmlBody will be used instead.
	InputEmailFile string `json:"InputEmailFile,omitempty"`
}
