/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersivePhishingApiClient

// Request to detect phishing from a URL
type AdvancedUrlDetectionRequest struct {
	// URL to check for phishing
	Url string `json:"Url,omitempty"`
	// Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
	CustomPolicyID string `json:"CustomPolicyID,omitempty"`
}
