/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersivePhishingApiClient

// Result of detecting phishing from a URL using AI
type PhishingDetectionUrlAdvancedResponse struct {
	// True if the result is not phishing (clean), and false otherwise
	CleanResult bool `json:"CleanResult,omitempty"`
	// Overall phishing risk level between 0.0 and 1.0
	PhishingRiskLevel float64 `json:"PhishingRiskLevel,omitempty"`
	// True if the URL is an SSRF threat
	IsSsrfThreat bool `json:"IsSsrfThreat,omitempty"`
	// True if the URL contains phishing threat risks, false otherwise
	ContainsPhishing bool `json:"ContainsPhishing,omitempty"`
	// True if the URL contains unsolicited sales, false otherwise
	ContainsUnsolicitedSales bool `json:"ContainsUnsolicitedSales,omitempty"`
	// True if the URL contains promotional content, false otherwise
	ContainsPromotionalContent bool `json:"ContainsPromotionalContent,omitempty"`
	// True if the URL contains a phishing attempt, false otherwise
	ContainsPhishingAttempt bool `json:"ContainsPhishingAttempt,omitempty"`
	// Rationale for why the conclusion was formed
	AnalysisRationale string `json:"AnalysisRationale,omitempty"`
}
