/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersivePhishingApiClient

// Result of detecting phishing using AI
type PhishingDetectionResponse struct {
	// True if the result is not phishing (clean), and false otherwise
	CleanResult bool `json:"CleanResult,omitempty"`
}
