/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersivePhishingApiClient

// AI advanced phishing detection request
type PhishingDetectionAdvancedRequest struct {
	// Input text string to detect phishing against
	InputString string `json:"InputString,omitempty"`
	// Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
	Model string `json:"Model,omitempty"`
}
