/*
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersivePhishingApiClient

// AI phishing detection request for basic text string analysis
type PhishingDetectionTextStringRequest struct {
	// Input text string to detect phishing against
	InputString string `json:"InputString,omitempty"`
	// Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
	Model string `json:"Model,omitempty"`
	// Optional: Set to true to include an analysis rationale in the response explaining why the content was or was not flagged.  Default is true.
	ProvideAnalysisRationale bool `json:"ProvideAnalysisRationale,omitempty"`
}
